version: '2'
services:
 elasticsearch:
  image: elasticsearch
  command: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  networks:
    - elk
 logstash:
  image: docker.elastic.co/logstash/logstash:5.5.1
  volumes:
    - $HOME/Documents/logs:/logs
  ports:
    - "5000:5000"
  networks:
    - elk
 kibana:
  image: kibana
  ports:
    - "5601:5601"
  networks:
    - elk

networks:
  elk:
